// biome-ignore-all lint/suspicious/noTemplateCurlyInString: these strings are shell code, where ${…} is shell syntax.
// Generated contract files (ADR-0007, AGENTS.md rule 4): plainport.json, the JSON Schemas in schemas/, and the zsh
// and bash completions in completions/. All come from the command registry and packages/contract; `bun run
// contract` writes them and `bun run contract --check` (CI) fails when a committed copy is stale. Never edit them
// by hand.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { contractJsonSchemas, EXIT, EXIT_CODE_MEANINGS, FINDINGS, PLAINPORT_JSON } from "@plainport/contract";
import { catalogJsonSchemas, configJsonSchemas } from "@plainport/core";
import { z } from "zod";
import { GLOBAL_OPTIONS } from "./gate.ts";
import { type AnyCommand, commandInfo, optionsOf, type Registry, registryProblems } from "./registry.ts";

/** The version of plainport.json's own shape. A breaking change to it bumps the number. */
export const MANIFEST_SCHEMA = "plainport.json/1";

/** Folders that hold only generated files: anything else found in them is stale. */
const GENERATED_DIRS = ["schemas", "completions"] as const;

/** Arguments are published as what a caller may pass (input); output and plans as what plainport prints. */
const jsonSchema = (schema: z.ZodType, io: "input" | "output") =>
  z.toJSONSchema(schema, { target: "draft-2020-12", io });

const json = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

export const manifest = (registry: Registry) => {
  const problems = registryProblems(
    registry,
    GLOBAL_OPTIONS.map((o) => o.name),
  );
  if (problems.length > 0) throw new Error(`the command registry is invalid:\n${problems.join("\n")}`);
  return {
    schema: MANIFEST_SCHEMA,
    plainport_json: PLAINPORT_JSON,
    globalOptions: GLOBAL_OPTIONS,
    commands: registry.map((command) => {
      const { examples, ...info } = commandInfo(command);
      return {
        ...info,
        arguments: jsonSchema(command.args, "input"),
        output: jsonSchema(command.output, "output"),
        plan: command.dryRun === false ? null : jsonSchema(command.dryRun.plan, "output"),
        examples,
      };
    }),
    exitCodes: Object.entries(EXIT).map(([name, code]) => ({
      code,
      name,
      meaning: EXIT_CODE_MEANINGS[code],
    })),
    findings: Object.entries(FINDINGS).map(([code, spec]) => ({ code, ...spec })),
  };
};

const sq = (text: string): string => `'${text.replaceAll("'", "'\\''")}'`;

const firstWords = (registry: Registry): string[] => [
  ...new Set(registry.map((c) => c.name.split(" ")[0] as string)),
];

/** For each group word (`root` in `root add`), its second words. */
const groups = (registry: Registry): Map<string, string[]> => {
  const out = new Map<string, string[]>();
  for (const command of registry) {
    const [group, sub] = command.name.split(" ");
    if (group !== undefined && sub !== undefined) out.set(group, [...(out.get(group) ?? []), sub]);
  }
  return out;
};

const optionWords = (command: AnyCommand): string =>
  [
    ...optionsOf(command).map((o) => `--${o.name}`),
    ...GLOBAL_OPTIONS.map((o) => `--${o.name}`),
    "--help",
  ].join(" ");

const HEADER = "# Generated by `bun run contract` from the command registry (packages/cli). Do not edit.";

export const bashCompletion = (registry: Registry): string => {
  const groupCases = [...groups(registry)].map(
    ([group, subs]) => `    ${group}) echo ${sq(subs.join(" "))} ;;`,
  );
  const twoWord = registry.filter((c) => c.name.includes(" ")).map((c) => sq(c.name));
  const oneWord = registry.filter((c) => !c.name.includes(" ")).map((c) => c.name);
  const optionCases = registry.map((c) => `    ${sq(c.name)}) opts=${sq(optionWords(c))} ;;`);
  return [
    HEADER,
    "# bash: source this file, or put it where bash-completion loads completions.",
    "",
    "# Candidates for the next word of a command name, given the name's words typed so far.",
    "_plainport_names() {",
    `  if [[ $# -eq 0 ]]; then echo ${sq(firstWords(registry).join(" "))}; return; fi`,
    ...(groupCases.length > 0
      ? ["  if [[ $# -eq 1 ]]; then", '    case "$1" in', ...groupCases, "    esac", "  fi"]
      : []),
    "}",
    "",
    "_plainport() {",
    '  local cur="${COMP_WORDS[COMP_CWORD]}"',
    "  local -a typed=()",
    "  local i",
    "  for ((i = 1; i < COMP_CWORD; i++)); do",
    '    [[ ${COMP_WORDS[i]} == -* ]] || typed+=("${COMP_WORDS[i]}")',
    "  done",
    '  local cmd="" used=0',
    ...(twoWord.length > 0
      ? [
          "  if [[ ${#typed[@]} -ge 2 ]]; then",
          `    case "\${typed[0]} \${typed[1]}" in ${twoWord.join("|")}) cmd="\${typed[0]} \${typed[1]}"; used=2 ;; esac`,
          "  fi",
        ]
      : []),
    "  if [[ -z $cmd && ${#typed[@]} -ge 1 ]]; then",
    `    case "\${typed[0]}" in ${oneWord.join("|") || "''"}) cmd="\${typed[0]}"; used=1 ;; esac`,
    "  fi",
    "  local opts=''",
    '  if [[ -n $cmd ]]; then case "$cmd" in',
    ...optionCases,
    "  esac; fi",
    "  if [[ $cur == -* ]]; then",
    `    [[ -n $cmd ]] || opts=${sq([...GLOBAL_OPTIONS.map((o) => `--${o.name}`), "--help", "--version"].join(" "))}`,
    '    COMPREPLY=($(compgen -W "$opts" -- "$cur"))',
    "  elif [[ -z $cmd ]]; then",
    '    COMPREPLY=($(compgen -W "$(_plainport_names "${typed[@]}")" -- "$cur"))',
    "  elif [[ $cmd == help ]]; then",
    '    COMPREPLY=($(compgen -W "$(_plainport_names "${typed[@]:used}")" -- "$cur"))',
    "  else",
    '    COMPREPLY=($(compgen -f -- "$cur"))',
    "  fi",
    "}",
    "",
    "complete -F _plainport plainport",
    "",
  ].join("\n");
};

export const zshCompletion = (registry: Registry): string => {
  const described = (pairs: [string, string][]) =>
    pairs.map(([word, summary]) => `      ${sq(`${word.replaceAll(":", "\\:")}:${summary}`)}`);
  const topLevel: [string, string][] = firstWords(registry).map((word) => {
    const command = registry.find((c) => c.name === word);
    return [word, command?.summary ?? `${word} commands`];
  });
  const groupCases = [...groups(registry)].map(([group, subs]) => [
    `    ${group})`,
    "      names=(",
    ...described(
      subs.map((sub) => [sub, registry.find((c) => c.name === `${group} ${sub}`)?.summary ?? ""]),
    ).map((line) => `  ${line}`),
    "      ) ;;",
  ]);
  const twoWord = registry.filter((c) => c.name.includes(" ")).map((c) => sq(c.name));
  const oneWord = registry.filter((c) => !c.name.includes(" ")).map((c) => c.name);
  const optionCases = registry.map((c) => `    ${sq(c.name)}) opts=(${optionWords(c)}) ;;`);
  return [
    "#compdef plainport",
    HEADER,
    "# zsh: put this file, named _plainport, in a folder on $fpath before compinit runs.",
    "",
    "_plainport_names() {",
    "  local -a names",
    "  if (( $# == 0 )); then",
    "    names=(",
    ...described(topLevel).map((line) => `  ${line}`),
    "    )",
    ...(groupCases.length > 0
      ? ["  elif (( $# == 1 )); then", '    case "$1" in', ...groupCases.flat(), "    esac"]
      : []),
    "  fi",
    "  (( ${#names} )) && _describe -t commands 'plainport command' names",
    "}",
    "",
    "_plainport() {",
    "  local cur=${words[CURRENT]}",
    "  local -a typed opts",
    "  typed=(${words[2,CURRENT-1]:#-*})",
    "  local cmd='' used=0",
    ...(twoWord.length > 0
      ? [
          `  if (( \${#typed} >= 2 )); then case "\${typed[1]} \${typed[2]}" in ${twoWord.join("|")}) cmd="\${typed[1]} \${typed[2]}"; used=2 ;; esac; fi`,
        ]
      : []),
    `  if [[ -z $cmd ]] && (( \${#typed} >= 1 )); then case "\${typed[1]}" in ${oneWord.join("|") || "''"}) cmd=\${typed[1]}; used=1 ;; esac; fi`,
    '  case "$cmd" in',
    ...optionCases,
    `    *) opts=(${[...GLOBAL_OPTIONS.map((o) => `--${o.name}`), "--help", "--version"].join(" ")}) ;;`,
    "  esac",
    "  if [[ $cur == -* ]]; then",
    "    compadd -- $opts",
    "  elif [[ -z $cmd ]]; then",
    "    _plainport_names $typed",
    "  elif [[ $cmd == help ]]; then",
    "    _plainport_names ${typed[used+1,-1]}",
    "  else",
    "    _files",
    "  fi",
    "}",
    "",
    '_plainport "$@"',
    "",
  ].join("\n");
};

/** Every generated file, keyed by its path from the repository root. */
export const generateFiles = (registry: Registry): Map<string, string> => {
  const files = new Map<string, string>();
  files.set("plainport.json", json(manifest(registry)));
  const schemas = { ...contractJsonSchemas(), ...configJsonSchemas(), ...catalogJsonSchemas() };
  for (const name of Object.keys(schemas).sort()) {
    files.set(`schemas/${name}.json`, json(schemas[name as keyof typeof schemas]));
  }
  files.set("completions/_plainport", zshCompletion(registry));
  files.set("completions/plainport.bash", bashCompletion(registry));
  return files;
};

const listGenerated = (root: string): string[] =>
  GENERATED_DIRS.flatMap((dir) =>
    existsSync(join(root, dir)) ? readdirSync(join(root, dir)).map((name) => `${dir}/${name}`) : [],
  );

/** Paths under `root` that differ from what the registry generates: changed, missing, or not generated at all. */
export const staleFiles = (root: string, registry: Registry): string[] => {
  const files = generateFiles(registry);
  const stale: string[] = [];
  for (const [path, text] of files) {
    const full = join(root, path);
    if (!existsSync(full) || readFileSync(full, "utf8") !== text) stale.push(path);
  }
  for (const path of listGenerated(root)) if (!files.has(path)) stale.push(path);
  return stale;
};

/** Writes every generated file under `root` and removes stale ones from the generated folders. */
export const writeFiles = (root: string, registry: Registry): string[] => {
  const stale = staleFiles(root, registry);
  const files = generateFiles(registry);
  for (const path of stale) {
    const full = join(root, path);
    const text = files.get(path);
    if (text === undefined) {
      rmSync(full, { force: true });
      continue;
    }
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, text);
  }
  return stale;
};
