// The Node ecosystem plugin (DESIGN.md "Plugin interfaces → Node plugin"). It detects package folders, proposes what
// an install or a build regenerates, and names the frozen install that brings the dependencies back. It reads the
// scan's manifest and each package.json, and runs nothing: the core decides what is stripped, and onload runs the
// install.
//
// An install root is a folder whose dependencies one install brings back: the project folder when it has a
// package.json, and any folder below it with both a package.json and a lockfile of its own (a frontend/ beside a
// Python backend). A workspace member (package.json `workspaces`, pnpm-workspace.yaml `packages`) is never one, stray
// lockfile or not: one install at the workspace root covers it.
//
// Proposals: every outermost node_modules; the framework caches .next, .nuxt, .svelte-kit, .turbo, .parcel-cache and
// .vercel/output; Yarn Berry's install state and cache (.yarn/cache, .yarn/unplugged, .yarn/install-state.gz,
// .pnp.cjs, .pnp.loader.mjs), kept by the core when committed for zero-installs; and dist/ or build/ beside a
// package.json only when one of its scripts writes them.

import { join } from "node:path";
import { type Finding, finding } from "@plainport/contract";
import {
  compilePatterns,
  type Detection,
  type EcosystemPlugin,
  type HydrateStep,
  type Manifest,
  type PatternSet,
  type ProjectDir,
  type StripCandidate,
  systemErrorCode,
} from "@plainport/core";
import { choosePackageManager, LOCKFILES, MANAGER_NAMES, type PackageManagerChoice } from "./detect.ts";
import { type OutputFolder, scriptWriting } from "./scripts.ts";

/** Framework output and caches, regenerated by a build or a dev server. A Map, so no folder name is a key by
 * inheritance (`constructor`, `toString`). */
const CACHES: ReadonlyMap<string, string> = new Map([
  [".next", "Next.js build output and cache; next build makes it again"],
  [".nuxt", "Nuxt's generated build files; nuxt build makes them again"],
  [".svelte-kit", "SvelteKit's generated files; vite build or dev makes them again"],
  [".turbo", "Turborepo's cache; turbo run fills it again"],
  [".parcel-cache", "Parcel's cache; parcel fills it again"],
  [".vercel/output", "Vercel's build output; vercel build makes it again"],
]);

/** Yarn Berry's install artefacts, inside a Yarn Berry install root. */
const BERRY = [".yarn/cache", ".yarn/unplugged", ".yarn/install-state.gz", ".pnp.cjs", ".pnp.loader.mjs"];

/** Folders holding nothing of the project's own packages: dependencies, git, Yarn, caches and build output. */
const NOT_PACKAGES = new Set([
  "node_modules",
  ".git",
  ".yarn",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".turbo",
  ".parcel-cache",
  "dist",
  "build",
]);

/** Whether an entry (its path split at "/") lies inside one of those folders, or inside .vercel/output. */
const inOwnOutput = (parts: readonly string[]): boolean =>
  parts
    .slice(0, -1)
    .some(
      (p, i) => NOT_PACKAGES.has(p) || (p === ".vercel" && parts[i + 1] === "output" && i + 2 < parts.length),
    );

interface Package {
  /** Its folder, relative; "" is the project folder. */
  folder: string;
  scripts: Record<string, unknown>;
  packageManager?: string;
  /** package.json's workspaces globs (array or { packages } form). */
  workspaces: string[];
}

interface InstallRoot {
  folder: string;
  choice: PackageManagerChoice;
  /** Its workspace members' globs, from package.json or pnpm-workspace.yaml, relative to the folder. */
  members: PatternSet;
}

interface Index {
  packages: Package[];
  installRoots: InstallRoot[];
  /** Package folder → the install that fills its node_modules: its own, or its workspace root's. */
  coveredBy: Map<string, InstallRoot>;
  /** Outermost node_modules folders. */
  nodeModules: string[];
  /** Cache folders: path → which cache. */
  caches: { path: string; name: string }[];
}

const at = (folder: string, name: string): string => (folder === "" ? name : `${folder}/${name}`);
const parentOf = (path: string): string => (path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "");
const within = (path: string, folder: string): boolean =>
  folder === "" || path === folder || path.startsWith(`${folder}/`);

const readPackage = async (project: ProjectDir, folder: string): Promise<Package> => {
  let parsed: unknown;
  try {
    parsed = JSON.parse(await project.fs.readText(join(project.dir, at(folder, "package.json"))));
  } catch (error) {
    // Unreadable or not JSON: a package with no scripts and no field, so nothing is proposed from it.
    if (!(error instanceof SyntaxError)) systemErrorCode(error);
    parsed = undefined;
  }
  const json = typeof parsed === "object" && parsed !== null ? (parsed as Record<string, unknown>) : {};
  const scripts = typeof json.scripts === "object" && json.scripts !== null ? json.scripts : {};
  const listed = Array.isArray(json.workspaces)
    ? json.workspaces
    : typeof json.workspaces === "object" && json.workspaces !== null
      ? (json.workspaces as Record<string, unknown>).packages
      : undefined;
  return {
    folder,
    scripts: scripts as Record<string, unknown>,
    ...(typeof json.packageManager === "string" ? { packageManager: json.packageManager } : {}),
    workspaces: Array.isArray(listed) ? listed.filter((g): g is string => typeof g === "string") : [],
  };
};

/** The `packages:` globs of a pnpm-workspace.yaml: the block list under that key, quotes removed. */
export const pnpmWorkspaceGlobs = (yaml: string): string[] => {
  const globs: string[] = [];
  let inPackages = false;
  for (const line of yaml.split(/\r?\n/)) {
    if (/^packages\s*:\s*$/.test(line)) inPackages = true;
    else if (/^\S/.test(line)) inPackages = false;
    else if (inPackages) {
      const item = /^\s+-\s*(['"]?)(.+?)\1\s*$/.exec(line)?.[2];
      if (item !== undefined) globs.push(item);
    }
  }
  return globs;
};

const readPnpmWorkspace = async (project: ProjectDir, folder: string): Promise<string[]> => {
  if (project.manifest.get(at(folder, "pnpm-workspace.yaml"))?.type !== "file") return [];
  try {
    return pnpmWorkspaceGlobs(
      await project.fs.readText(join(project.dir, at(folder, "pnpm-workspace.yaml"))),
    );
  } catch (error) {
    // Unreadable: no members known, so a member with its own lockfile installs on its own.
    systemErrorCode(error);
    return [];
  }
};

const indexes = new WeakMap<Manifest, Promise<Index>>();

const buildIndex = async (project: ProjectDir): Promise<Index> => {
  const { manifest } = project;
  const folders: string[] = [];
  const nodeModules: string[] = [];
  const caches: Index["caches"] = [];
  for (const entry of manifest) {
    const parts = entry.path.split("/");
    // Inside dependencies, .git, Yarn's own folder or a build's output (.next/standalone, .vercel/output's
    // functions, dist/): nothing there is the project's own; it leaves or stays with the folder holding it.
    if (inOwnOutput(parts)) continue;
    const name = parts.at(-1) as string;
    if (entry.type === "dir" && name === "node_modules") nodeModules.push(entry.path);
    else if (entry.type === "dir" && CACHES.has(name)) caches.push({ path: entry.path, name });
    else if (
      entry.type === "dir" &&
      (entry.path === ".vercel/output" || entry.path.endsWith("/.vercel/output"))
    )
      caches.push({ path: entry.path, name: ".vercel/output" });
    else if (entry.type === "file" && name === "package.json") folders.push(parentOf(entry.path));
  }
  const packages = await Promise.all(folders.sort().map((folder) => readPackage(project, folder)));
  const installRoots: InstallRoot[] = [];
  const coveredBy = new Map<string, InstallRoot>();
  for (const pkg of packages) {
    // A workspace member is installed by its workspace root's one install, stray lockfile or not.
    const workspace = installRoots.find(
      (root) =>
        within(pkg.folder, root.folder) &&
        root.members.matches(
          root.folder === "" ? pkg.folder : pkg.folder.slice(root.folder.length + 1),
          "dir",
        ),
    );
    if (pkg.folder !== "" && workspace !== undefined) {
      coveredBy.set(pkg.folder, workspace);
      continue;
    }
    const lockfiles = new Set(
      LOCKFILES.filter((name) => manifest.get(at(pkg.folder, name))?.type === "file"),
    );
    if (pkg.folder !== "" && lockfiles.size === 0) continue;
    const choice = choosePackageManager({
      lockfiles,
      yarnrc: manifest.get(at(pkg.folder, ".yarnrc.yml")) !== undefined,
      ...(pkg.packageManager === undefined ? {} : { packageManager: pkg.packageManager }),
    });
    const globs = [...pkg.workspaces, ...(await readPnpmWorkspace(project, pkg.folder))];
    const root = { folder: pkg.folder, choice, members: compilePatterns(globs) };
    installRoots.push(root);
    coveredBy.set(pkg.folder, root);
  }
  return { packages, installRoots, coveredBy, nodeModules, caches };
};

const indexOf = (project: ProjectDir): Promise<Index> => {
  let index = indexes.get(project.manifest);
  if (index === undefined) {
    index = buildIndex(project);
    indexes.set(project.manifest, index);
  }
  return index;
};

/** The install root a path belongs to: the innermost one holding it. */
const installed = (root: InstallRoot): string =>
  `installed dependencies; ${root.choice.argv.join(" ")}${root.folder === "" ? "" : ` in ${root.folder}`}${root.choice.lockfile === undefined ? "" : ` from ${root.choice.lockfile}`} puts them back`;

const where = (folder: string): string => (folder === "" ? "the project" : folder);

export const nodePlugin: EcosystemPlugin = {
  id: "node",

  detect: async (project): Promise<Detection | null> => {
    const index = await indexOf(project);
    if (index.installRoots.length === 0) return null;
    return {
      plugin: "node",
      summary: index.installRoots
        .map(
          (r) =>
            `${MANAGER_NAMES[r.choice.manager]} (${r.choice.lockfile ?? "no lockfile"})${r.folder === "" ? "" : ` in ${r.folder}`}`,
        )
        .join(", "),
    };
  },

  strip: async (ctx): Promise<StripCandidate[]> => {
    const index = await indexOf(ctx);
    // A node_modules is claimed only where an install puts it back: beside an install root's package.json or a
    // workspace member's. Any other is declined, so it stays, and the plan says why.
    const candidates: StripCandidate[] = index.nodeModules.map((path) => {
      const folder = parentOf(path);
      const root = index.coveredBy.get(folder);
      if (root !== undefined) return { path, reason: installed(root), kind: "deps" };
      const isPackage = index.packages.some((pkg) => pkg.folder === folder);
      return {
        path,
        reason: "installed dependencies",
        kind: "deps",
        declined: isPackage
          ? `no install puts it back: ${where(folder)} has no lockfile and is in no workspace`
          : "no install puts it back: there is no package.json beside it",
      };
    });
    for (const root of index.installRoots) {
      if (root.choice.manager !== "yarn-berry") continue;
      for (const name of BERRY) {
        const path = at(root.folder, name);
        if (ctx.manifest.get(path) !== undefined)
          candidates.push({ path, reason: installed(root), kind: "deps" });
      }
    }
    for (const cache of index.caches)
      candidates.push({ path: cache.path, reason: CACHES.get(cache.name) as string, kind: "output" });
    for (const pkg of index.packages) {
      for (const folder of ["dist", "build"] as OutputFolder[]) {
        const path = at(pkg.folder, folder);
        if (ctx.manifest.get(path)?.type !== "dir") continue;
        const script = scriptWriting(pkg.scripts, folder);
        if (script === undefined) continue;
        candidates.push({
          path,
          reason: `build output; the ${script} script (${String(pkg.scripts[script])}) makes it again`,
          kind: "output",
        });
      }
    }
    return candidates;
  },

  preflight: async (ctx): Promise<Finding[]> => {
    const index = await indexOf(ctx);
    const findings: Finding[] = [];
    for (const root of index.installRoots) {
      const { choice } = root;
      const manager = MANAGER_NAMES[choice.manager];
      if (choice.problem?.kind === "no-lockfile") {
        findings.push(
          finding("deps.no-lockfile", {
            // Why this node_modules goes when a sub-package's without a lockfile stays: a project (or a package with
            // a lockfile of another manager) is still installed, only unfrozen; a sub-package with no lockfile of
            // its own is installed by nothing, so its node_modules is declined.
            message: `${where(root.folder)} has no ${manager} lockfile, so onload reinstalls ${root.folder === "" ? "the project's" : "its"} dependencies fresh (${choice.argv.join(" ")}), not frozen, and may pick newer versions; packages below it with no lockfile keep their node_modules, since nothing would install them`,
            paths: [at(root.folder, "package.json")],
            fix: `run ${choice.argv.join(" ")} once${root.folder === "" ? "" : ` in ${root.folder}`} and commit the lockfile it writes, or keep the installed dependencies in the snapshot with --keep-deps`,
          }),
        );
      } else if (choice.problem?.kind === "ambiguous") {
        findings.push(
          finding("deps.ambiguous", {
            message: `${where(root.folder)} holds ${choice.problem.lockfiles.join(" and ")} and no packageManager field, so onload will use ${manager} (${choice.lockfile})`,
            paths: choice.problem.lockfiles.map((name) => at(root.folder, name)),
            fix: `set "packageManager" in ${at(root.folder, "package.json")} (e.g. "pnpm@9.12.0"), or delete the lockfile that is not in use`,
          }),
        );
      }
    }
    return findings;
  },

  hydrate: async (ctx) => {
    const index = await indexOf(ctx);
    const steps: HydrateStep[] = index.installRoots.map((root) => ({
      path: root.folder,
      command: root.choice.argv.join(" "),
      argv: [...root.choice.argv],
    }));
    return { steps };
  },
};
