// The Node ecosystem plugin (DESIGN.md "Plugin interfaces → Node plugin"). It detects package folders, proposes what
// an install or a build regenerates, and names the frozen install that brings the dependencies back. It reads the
// scan's manifest and each package.json, and runs nothing: the core decides what is stripped, and onload runs the
// install.
//
// An install root is a folder whose dependencies one install brings back: the project folder when it has a
// package.json, and any folder below it with both a package.json and a lockfile of its own (a frontend/ beside a
// Python backend). A monorepo's workspaces have no lockfile of their own, so one install at the root covers them.
//
// Proposals: every outermost node_modules; the framework caches .next, .nuxt, .svelte-kit, .turbo, .parcel-cache and
// .vercel/output; Yarn Berry's install state and cache (.yarn/cache, .yarn/unplugged, .yarn/install-state.gz,
// .pnp.cjs, .pnp.loader.mjs), kept by the core when committed for zero-installs; and dist/ or build/ beside a
// package.json only when one of its scripts writes them.

import { join } from "node:path";
import { type Finding, finding } from "@plainport/contract";
import {
  type Detection,
  type EcosystemPlugin,
  type HydrateStep,
  type Manifest,
  type ProjectDir,
  type StripCandidate,
  systemErrorCode,
} from "@plainport/core";
import { choosePackageManager, LOCKFILES, MANAGER_NAMES, type PackageManagerChoice } from "./detect.ts";
import { type OutputFolder, scriptWriting } from "./scripts.ts";

/** Framework output and caches, regenerated by a build or a dev server. */
const CACHES: Readonly<Record<string, string>> = {
  ".next": "Next.js build output and cache; next build makes it again",
  ".nuxt": "Nuxt's generated build files; nuxt build makes them again",
  ".svelte-kit": "SvelteKit's generated files; vite build or dev makes them again",
  ".turbo": "Turborepo's cache; turbo run fills it again",
  ".parcel-cache": "Parcel's cache; parcel fills it again",
  ".vercel/output": "Vercel's build output; vercel build makes it again",
};

/** Yarn Berry's install artefacts, inside a Yarn Berry install root. */
const BERRY = [".yarn/cache", ".yarn/unplugged", ".yarn/install-state.gz", ".pnp.cjs", ".pnp.loader.mjs"];

/** Folders whose package.json files are not packages of the project: dependencies, caches, outputs. */
const NOT_PACKAGES = new Set([
  "node_modules",
  ".git",
  ".yarn",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".turbo",
  "dist",
  "build",
]);

interface Package {
  /** Its folder, relative; "" is the project folder. */
  folder: string;
  scripts: Record<string, unknown>;
  packageManager?: string;
}

interface InstallRoot {
  folder: string;
  choice: PackageManagerChoice;
}

interface Index {
  packages: Package[];
  installRoots: InstallRoot[];
  /** Outermost node_modules folders. */
  nodeModules: string[];
  /** Cache folders: path → which cache. */
  caches: { path: string; name: string }[];
}

const at = (folder: string, name: string): string => (folder === "" ? name : `${folder}/${name}`);
const parentOf = (path: string): string => (path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "");
const within = (path: string, folder: string): boolean =>
  folder === "" || path === folder || path.startsWith(`${folder}/`);

const readPackage = async (project: ProjectDir, folder: string): Promise<Package> => {
  let parsed: unknown;
  try {
    parsed = JSON.parse(await project.fs.readText(join(project.dir, at(folder, "package.json"))));
  } catch (error) {
    // Unreadable or not JSON: a package with no scripts and no field, so nothing is proposed from it.
    if (!(error instanceof SyntaxError)) systemErrorCode(error);
    parsed = undefined;
  }
  const json = typeof parsed === "object" && parsed !== null ? (parsed as Record<string, unknown>) : {};
  const scripts = typeof json.scripts === "object" && json.scripts !== null ? json.scripts : {};
  return {
    folder,
    scripts: scripts as Record<string, unknown>,
    ...(typeof json.packageManager === "string" ? { packageManager: json.packageManager } : {}),
  };
};

const indexes = new WeakMap<Manifest, Promise<Index>>();

const buildIndex = async (project: ProjectDir): Promise<Index> => {
  const { manifest } = project;
  const folders: string[] = [];
  const nodeModules: string[] = [];
  const caches: Index["caches"] = [];
  for (const entry of manifest) {
    const parts = entry.path.split("/");
    if (parts.slice(0, -1).includes("node_modules") || parts.includes(".git")) continue;
    const name = parts.at(-1) as string;
    if (entry.type === "dir" && name === "node_modules") nodeModules.push(entry.path);
    else if (entry.type === "dir" && name in CACHES) caches.push({ path: entry.path, name });
    else if (entry.type === "dir" && entry.path.endsWith(".vercel/output"))
      caches.push({ path: entry.path, name: ".vercel/output" });
    else if (
      entry.type === "file" &&
      name === "package.json" &&
      !parts.slice(0, -1).some((p) => NOT_PACKAGES.has(p))
    )
      folders.push(parentOf(entry.path));
  }
  const packages = await Promise.all(folders.sort().map((folder) => readPackage(project, folder)));
  const installRoots: InstallRoot[] = [];
  for (const pkg of packages) {
    const lockfiles = new Set(
      LOCKFILES.filter((name) => manifest.get(at(pkg.folder, name))?.type === "file"),
    );
    if (pkg.folder !== "" && lockfiles.size === 0) continue;
    const choice = choosePackageManager({
      lockfiles,
      yarnrc: manifest.get(at(pkg.folder, ".yarnrc.yml")) !== undefined,
      ...(pkg.packageManager === undefined ? {} : { packageManager: pkg.packageManager }),
    });
    installRoots.push({ folder: pkg.folder, choice });
  }
  return { packages, installRoots, nodeModules, caches };
};

const indexOf = (project: ProjectDir): Promise<Index> => {
  let index = indexes.get(project.manifest);
  if (index === undefined) {
    index = buildIndex(project);
    indexes.set(project.manifest, index);
  }
  return index;
};

/** The install root a path belongs to: the innermost one holding it. */
const rootOf = (index: Index, path: string): InstallRoot | undefined =>
  index.installRoots
    .filter((r) => within(path, r.folder))
    .reduce<InstallRoot | undefined>(
      (best, r) => (best === undefined || r.folder.length > best.folder.length ? r : best),
      undefined,
    );

const installed = (root: InstallRoot | undefined): string =>
  root === undefined
    ? "installed dependencies; a package install puts them back"
    : `installed dependencies; ${root.choice.argv.join(" ")}${root.choice.lockfile === undefined ? "" : ` from ${root.choice.lockfile}`} puts them back`;

const where = (folder: string): string => (folder === "" ? "the project" : folder);

export const nodePlugin: EcosystemPlugin = {
  id: "node",

  detect: async (project): Promise<Detection | null> => {
    const index = await indexOf(project);
    if (index.installRoots.length === 0) return null;
    return {
      plugin: "node",
      summary: index.installRoots
        .map(
          (r) =>
            `${MANAGER_NAMES[r.choice.manager]} (${r.choice.lockfile ?? "no lockfile"})${r.folder === "" ? "" : ` in ${r.folder}`}`,
        )
        .join(", "),
    };
  },

  strip: async (ctx): Promise<StripCandidate[]> => {
    const index = await indexOf(ctx);
    const candidates: StripCandidate[] = index.nodeModules.map((path) => ({
      path,
      reason: installed(rootOf(index, path)),
      kind: "deps",
    }));
    for (const root of index.installRoots) {
      if (root.choice.manager !== "yarn-berry") continue;
      for (const name of BERRY) {
        const path = at(root.folder, name);
        if (ctx.manifest.get(path) !== undefined)
          candidates.push({ path, reason: installed(root), kind: "deps" });
      }
    }
    for (const cache of index.caches)
      candidates.push({ path: cache.path, reason: CACHES[cache.name] as string, kind: "output" });
    for (const pkg of index.packages) {
      for (const folder of ["dist", "build"] as OutputFolder[]) {
        const path = at(pkg.folder, folder);
        if (ctx.manifest.get(path)?.type !== "dir") continue;
        const script = scriptWriting(pkg.scripts, folder);
        if (script === undefined) continue;
        candidates.push({
          path,
          reason: `build output; the ${script} script (${String(pkg.scripts[script])}) makes it again`,
          kind: "output",
        });
      }
    }
    return candidates;
  },

  preflight: async (ctx): Promise<Finding[]> => {
    const index = await indexOf(ctx);
    const findings: Finding[] = [];
    for (const root of index.installRoots) {
      const { choice } = root;
      const manager = MANAGER_NAMES[choice.manager];
      if (choice.problem?.kind === "no-lockfile") {
        findings.push(
          finding("deps.no-lockfile", {
            message: `${where(root.folder)} has no ${manager} lockfile, so onload would install fresh dependency versions (${choice.argv.join(" ")})`,
            paths: [at(root.folder, "package.json")],
            fix: `run ${choice.argv.join(" ")} once${root.folder === "" ? "" : ` in ${root.folder}`} and commit the lockfile it writes, or keep the installed dependencies in the snapshot with --keep-deps`,
          }),
        );
      } else if (choice.problem?.kind === "ambiguous") {
        findings.push(
          finding("deps.ambiguous", {
            message: `${where(root.folder)} holds ${choice.problem.lockfiles.join(" and ")} and no packageManager field, so onload will use ${manager} (${choice.lockfile})`,
            paths: choice.problem.lockfiles.map((name) => at(root.folder, name)),
            fix: `set "packageManager" in ${at(root.folder, "package.json")} (e.g. "pnpm@9.12.0"), or delete the lockfile that is not in use`,
          }),
        );
      }
    }
    return findings;
  },

  hydrate: async (ctx) => {
    const index = await indexOf(ctx);
    const steps: HydrateStep[] = index.installRoots.map((root) => ({
      path: root.folder,
      command: root.choice.argv.join(" "),
      argv: [...root.choice.argv],
    }));
    return { steps };
  },
};
