# Generated by `bun run contract` from the command registry (packages/cli). Do not edit.
# bash: source this file, or put it where bash-completion loads completions.

# Candidates for the next word of a command name, given the name's words typed so far.
_plainport_names() {
  if [[ $# -eq 0 ]]; then echo 'help init offload onload hydrate dehydrate root version'; return; fi
  if [[ $# -eq 1 ]]; then
    case "$1" in
    root) echo 'add bind list scan' ;;
    esac
  fi
}

_plainport() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local -a typed=()
  local i
  for ((i = 1; i < COMP_CWORD; i++)); do
    [[ ${COMP_WORDS[i]} == -* ]] || typed+=("${COMP_WORDS[i]}")
  done
  local cmd="" used=0
  if [[ ${#typed[@]} -ge 2 ]]; then
    case "${typed[0]} ${typed[1]}" in 'root add'|'root bind'|'root list'|'root scan') cmd="${typed[0]} ${typed[1]}"; used=2 ;; esac
  fi
  if [[ -z $cmd && ${#typed[@]} -ge 1 ]]; then
    case "${typed[0]}" in help|init|offload|onload|hydrate|dehydrate|version) cmd="${typed[0]}"; used=1 ;; esac
  fi
  local opts=''
  if [[ -n $cmd ]]; then case "$cmd" in
    'help') opts='--json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'init') opts='--root --store-path --store-secret --device --json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'offload') opts='--plan --keep-deps --allow --json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'onload') opts='--to --snapshot --no-hydrate --json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'hydrate') opts='--json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'dehydrate') opts='--json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'root add') opts='--label --create --json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'root bind') opts='--device --create --json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'root list') opts='--json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'root scan') opts='--json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
    'version') opts='--json --yes --no-input --dry-run --store --config --quiet --verbose --help' ;;
  esac; fi
  if [[ $cur == -* ]]; then
    [[ -n $cmd ]] || opts='--json --yes --no-input --dry-run --store --config --quiet --verbose --help --version'
    COMPREPLY=($(compgen -W "$opts" -- "$cur"))
  elif [[ -z $cmd ]]; then
    COMPREPLY=($(compgen -W "$(_plainport_names "${typed[@]}")" -- "$cur"))
  elif [[ $cmd == help ]]; then
    COMPREPLY=($(compgen -W "$(_plainport_names "${typed[@]:used}")" -- "$cur"))
  else
    COMPREPLY=($(compgen -f -- "$cur"))
  fi
}

complete -F _plainport plainport
